var hierarchy =
[
    [ "wykobi::bezier_coefficients< T, Dimension, Type >", "structwykobi_1_1bezier__coefficients.html", null ],
    [ "wykobi::algorithm::convex_hull_graham_scan< T >", "structwykobi_1_1algorithm_1_1convex__hull__graham__scan.html", null ],
    [ "wykobi::algorithm::convex_hull_graham_scan< point2d< T > >", "structwykobi_1_1algorithm_1_1convex__hull__graham__scan_3_01point2d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::algorithm::convex_hull_jarvis_march< T >", "structwykobi_1_1algorithm_1_1convex__hull__jarvis__march.html", null ],
    [ "wykobi::algorithm::convex_hull_jarvis_march< point2d< T > >", "structwykobi_1_1algorithm_1_1convex__hull__jarvis__march_3_01point2d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::algorithm::convex_hull_melkman< T >", "structwykobi_1_1algorithm_1_1convex__hull__melkman.html", null ],
    [ "wykobi::algorithm::convex_hull_melkman< point2d< Type > >", "structwykobi_1_1algorithm_1_1convex__hull__melkman_3_01point2d_3_01Type_01_4_01_4.html", null ],
    [ "wykobi::algorithm::covariance_matrix< T >", "structwykobi_1_1algorithm_1_1covariance__matrix.html", null ],
    [ "wykobi::algorithm::covariance_matrix< point2d< T > >", "structwykobi_1_1algorithm_1_1covariance__matrix_3_01point2d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::algorithm::covariance_matrix< point3d< T > >", "structwykobi_1_1algorithm_1_1covariance__matrix_3_01point3d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::define_bezier_type< T, Dimension, BType >", "classwykobi_1_1define__bezier__type.html", null ],
    [ "wykobi::define_bezier_type< T, 2, eCubicBezier >", "classwykobi_1_1define__bezier__type_3_01T_00_012_00_01eCubicBezier_01_4.html", null ],
    [ "wykobi::define_bezier_type< T, 2, eQuadraticBezier >", "classwykobi_1_1define__bezier__type_3_01T_00_012_00_01eQuadraticBezier_01_4.html", null ],
    [ "wykobi::define_bezier_type< T, 3, eCubicBezier >", "classwykobi_1_1define__bezier__type_3_01T_00_013_00_01eCubicBezier_01_4.html", null ],
    [ "wykobi::define_bezier_type< T, 3, eQuadraticBezier >", "classwykobi_1_1define__bezier__type_3_01T_00_013_00_01eQuadraticBezier_01_4.html", null ],
    [ "wykobi::define_eigen_vector< T, Dimension >", "classwykobi_1_1define__eigen__vector.html", null ],
    [ "wykobi::define_eigen_vector< double, 2 >", "classwykobi_1_1define__eigen__vector_3_01double_00_012_01_4.html", null ],
    [ "wykobi::define_eigen_vector< double, 3 >", "classwykobi_1_1define__eigen__vector_3_01double_00_013_01_4.html", null ],
    [ "wykobi::define_point_type< T, Dimension >", "classwykobi_1_1define__point__type.html", null ],
    [ "wykobi::define_point_type< T, 2 >", "classwykobi_1_1define__point__type_3_01T_00_012_01_4.html", null ],
    [ "wykobi::define_point_type< T, 3 >", "classwykobi_1_1define__point__type_3_01T_00_013_01_4.html", null ],
    [ "wykobi::define_vector_type< T, Dimension >", "classwykobi_1_1define__vector__type.html", null ],
    [ "wykobi::define_vector_type< T, 2 >", "classwykobi_1_1define__vector__type_3_01T_00_012_01_4.html", null ],
    [ "wykobi::define_vector_type< T, 3 >", "classwykobi_1_1define__vector__type_3_01T_00_013_01_4.html", null ],
    [ "wykobi::algorithm::generate_axis_projection_descriptor< T >", "structwykobi_1_1algorithm_1_1generate__axis__projection__descriptor.html", null ],
    [ "wykobi::geometric_entity", "classwykobi_1_1geometric__entity.html", [
      [ "wykobi::box< T, Dimension >", "classwykobi_1_1box.html", null ],
      [ "wykobi::circle< T >", "classwykobi_1_1circle.html", null ],
      [ "wykobi::circular_arc< T >", "classwykobi_1_1circular__arc.html", null ],
      [ "wykobi::cubic_bezier< T, Dimension >", "classwykobi_1_1cubic__bezier.html", null ],
      [ "wykobi::curve_point< T, Dimension >", "classwykobi_1_1curve__point.html", null ],
      [ "wykobi::hypersphere< T, Dimension >", "classwykobi_1_1hypersphere.html", null ],
      [ "wykobi::line< T, Dimension >", "classwykobi_1_1line.html", null ],
      [ "wykobi::plane< T, Dimension >", "classwykobi_1_1plane.html", null ],
      [ "wykobi::point2d< T >", "classwykobi_1_1point2d.html", [
        [ "wykobi::vector2d< T >", "classwykobi_1_1vector2d.html", null ]
      ] ],
      [ "wykobi::point3d< T >", "classwykobi_1_1point3d.html", [
        [ "wykobi::vector3d< T >", "classwykobi_1_1vector3d.html", null ]
      ] ],
      [ "wykobi::polygon< T, Dimension >", "classwykobi_1_1polygon.html", null ],
      [ "wykobi::quadix< T, Dimension >", "classwykobi_1_1quadix.html", null ],
      [ "wykobi::quadratic_bezier< T, Dimension >", "classwykobi_1_1quadratic__bezier.html", null ],
      [ "wykobi::ray< T, Dimension >", "classwykobi_1_1ray.html", null ],
      [ "wykobi::rectangle< T >", "classwykobi_1_1rectangle.html", null ],
      [ "wykobi::segment< T, Dimension >", "classwykobi_1_1segment.html", null ],
      [ "wykobi::sphere< T >", "classwykobi_1_1sphere.html", null ],
      [ "wykobi::triangle< T, Dimension >", "classwykobi_1_1triangle.html", null ]
    ] ],
    [ "wykobi::algorithm::isotropic_normalization< T >", "structwykobi_1_1algorithm_1_1isotropic__normalization.html", null ],
    [ "wykobi::algorithm::isotropic_normalization< point2d< T > >", "structwykobi_1_1algorithm_1_1isotropic__normalization_3_01point2d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::algorithm::isotropic_normalization< point3d< T > >", "structwykobi_1_1algorithm_1_1isotropic__normalization_3_01point3d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::matrix< T, M, N >", "classwykobi_1_1matrix.html", null ],
    [ "wykobi::algorithm::naive_group_intersections< T >", "structwykobi_1_1algorithm_1_1naive__group__intersections.html", null ],
    [ "wykobi::algorithm::naive_group_intersections< circle< T > >", "structwykobi_1_1algorithm_1_1naive__group__intersections_3_01circle_3_01T_01_4_01_4.html", null ],
    [ "wykobi::algorithm::naive_group_intersections< segment< T, 2 > >", "structwykobi_1_1algorithm_1_1naive__group__intersections_3_01segment_3_01T_00_012_01_4_01_4.html", null ],
    [ "wykobi::algorithm::naive_group_intersections< segment< T, 3 > >", "structwykobi_1_1algorithm_1_1naive__group__intersections_3_01segment_3_01T_00_013_01_4_01_4.html", null ],
    [ "wykobi::algorithm::naive_minimum_bounding_ball< T >", "structwykobi_1_1algorithm_1_1naive__minimum__bounding__ball.html", null ],
    [ "wykobi::algorithm::naive_minimum_bounding_ball< point2d< T > >", "structwykobi_1_1algorithm_1_1naive__minimum__bounding__ball_3_01point2d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::algorithm::naive_minimum_bounding_ball_with_ch_filter< T >", "structwykobi_1_1algorithm_1_1naive__minimum__bounding__ball__with__ch__filter.html", null ],
    [ "wykobi::algorithm::naive_minimum_bounding_ball_with_ch_filter< point2d< T > >", "structwykobi_1_1algorithm_1_1naive__minimum__bounding__ball__with__ch__filter_3_01point2d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::algorithm::ordered_polygon< T >", "structwykobi_1_1algorithm_1_1ordered__polygon.html", null ],
    [ "wykobi::algorithm::ordered_polygon< point2d< T > >", "structwykobi_1_1algorithm_1_1ordered__polygon_3_01point2d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::pointnd< T, D >", "classwykobi_1_1pointnd.html", null ],
    [ "wykobi::algorithm::polygon_triangulate< T >", "structwykobi_1_1algorithm_1_1polygon__triangulate.html", null ],
    [ "wykobi::algorithm::polygon_triangulate< point2d< T > >", "structwykobi_1_1algorithm_1_1polygon__triangulate_3_01point2d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::algorithm::randomized_minimum_bounding_ball< T >", "structwykobi_1_1algorithm_1_1randomized__minimum__bounding__ball.html", null ],
    [ "wykobi::algorithm::randomized_minimum_bounding_ball< point2d< T > >", "structwykobi_1_1algorithm_1_1randomized__minimum__bounding__ball_3_01point2d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::algorithm::randomized_minimum_bounding_ball_with_ch_filter< T >", "structwykobi_1_1algorithm_1_1randomized__minimum__bounding__ball__with__ch__filter.html", null ],
    [ "wykobi::algorithm::randomized_minimum_bounding_ball_with_ch_filter< point2d< T > >", "structwykobi_1_1algorithm_1_1randomized__minimum__bounding__ball__with__ch__filter_3_01point2d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::algorithm::remove_duplicates< T >", "structwykobi_1_1algorithm_1_1remove__duplicates.html", null ],
    [ "wykobi::algorithm::ritter_minimum_bounding_ball< T >", "structwykobi_1_1algorithm_1_1ritter__minimum__bounding__ball.html", null ],
    [ "wykobi::algorithm::ritter_minimum_bounding_ball< point2d< T > >", "structwykobi_1_1algorithm_1_1ritter__minimum__bounding__ball_3_01point2d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::algorithm::ritter_minimum_bounding_ball< point3d< T > >", "structwykobi_1_1algorithm_1_1ritter__minimum__bounding__ball_3_01point3d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::algorithm::ritter_minimum_bounding_ball_with_ch_filter< T >", "structwykobi_1_1algorithm_1_1ritter__minimum__bounding__ball__with__ch__filter.html", null ],
    [ "wykobi::algorithm::ritter_minimum_bounding_ball_with_ch_filter< point2d< T > >", "structwykobi_1_1algorithm_1_1ritter__minimum__bounding__ball__with__ch__filter_3_01point2d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::algorithm::sutherland_hodgman_polygon_clipper< T >", "structwykobi_1_1algorithm_1_1sutherland__hodgman__polygon__clipper.html", null ],
    [ "wykobi::algorithm::sutherland_hodgman_polygon_clipper< point2d< T > >", "structwykobi_1_1algorithm_1_1sutherland__hodgman__polygon__clipper_3_01point2d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::algorithm::sutherland_hodgman_polygon_clipper_engine< T >", "structwykobi_1_1algorithm_1_1sutherland__hodgman__polygon__clipper__engine.html", null ],
    [ "wykobi::algorithm::sutherland_hodgman_polygon_clipper_engine< point2d< T > >", "structwykobi_1_1algorithm_1_1sutherland__hodgman__polygon__clipper__engine_3_01point2d_3_01T_01_4_01_4.html", null ],
    [ "wykobi::trig_luts< T >", "classwykobi_1_1trig__luts.html", null ],
    [ "wykobi::vectornd< T, D >", "classwykobi_1_1vectornd.html", null ],
    [ "wykobi::wykobi_graphics_net< T >", "classwykobi_1_1wykobi__graphics__net.html", null ],
    [ "wykobi::wykobi_graphics_opengl< T >", "classwykobi_1_1wykobi__graphics__opengl.html", null ],
    [ "wykobi::wykobi_graphics_vcl< T >", "classwykobi_1_1wykobi__graphics__vcl.html", null ],
    [ "wykobi_window", "classwykobi__window.html", null ]
];